#!/usr/bin/env bash
# Copy non-standard vault files (JSON, CSV, DOCX, YAML) to public/notes/
# without extensions, matching the link format generated by starlight-obsidian.

set -euo pipefail

if [ -n "${SKIP_OBSIDIAN_GENERATION:-}" ]; then
  echo "SKIP_OBSIDIAN_GENERATION is set, skipping vault extras copy"
  exit 0
fi

VAULT="/home/arcangelo/Documents/obsidian"

if [ ! -d "$VAULT" ]; then
  echo "Vault directory not found, skipping vault extras copy"
  exit 0
fi

DEST="public/notes"
EXTENSIONS=("json" "csv" "docx" "yml" "yaml")
INCLUDED_DIRS=("attachments" "Tu vuo far el phdino")

NAME_MATCHES=()
for i in "${!EXTENSIONS[@]}"; do
  if [ "$i" -gt 0 ]; then
    NAME_MATCHES+=(-o)
  fi
  NAME_MATCHES+=(-name "*.${EXTENSIONS[$i]}")
done

count=0
for dir in "${INCLUDED_DIRS[@]}"; do
  src="$VAULT/$dir"
  [ -d "$src" ] || continue
  while IFS= read -r file; do
    rel="${file#"$VAULT/"}"
    dest_path="$DEST/${rel%.*}"
    mkdir -p "$(dirname "$dest_path")"
    cp "$file" "$dest_path"
    count=$((count + 1))
  done < <(find "$src" -type f \( "${NAME_MATCHES[@]}" \))
done

echo "Copied $count vault extras to $DEST"
